apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}  # Keep this simple to match existing pods
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}  # Simple label matching selector
        {{- include "ignite-app.labels" . | nindent 8 }}  # Additional Helm labels
    spec:
      containers:
      - name: ignite-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
          name: http
        resources:
          {{- toYaml .Values.resources | nindent 10 }}